// Types of Units
1. Absulte Css
  px - fixed
  
2. Relative CSS

 em - Relative to the font size of the elements ( 2em means 2 times of the current font)
 ch  - Relative to the width of 0
 rem  - Relative to the font size of root elements 
 vw -  Relative to the 1% of width of ViewPort
 vh  - 1% of hight of ViewPort
 vmin  - Relative to the 1% of ViewPort of Smaler Dimensons
 vmax  - 1% of large Dimensons 
 %  - Relative to the Parents Elements 
 ex  - Relative to the x-Hight of the current Elements 
